// <auto-generated />
using System;
using CarCareHub.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCareHub.Services.Migrations
{
    [DbContext(typeof(CchV2AliContext))]
    [Migration("20240304211918_mii")]
    partial class mii
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarCareHub.Services.Database.Autoservi", b =>
                {
                    b.Property<int>("AutoservisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AutoservisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoservisId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adresa");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<int?>("GradId")
                        .HasColumnType("int")
                        .HasColumnName("gradID");

                    b.Property<string>("Jib")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("jib");

                    b.Property<string>("Mbs")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MBS");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password_");

                    b.Property<string>("SlikaProfila")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("slika_Profila");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefon");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int")
                        .HasColumnName("ulogaID");

                    b.Property<int?>("UslugeId")
                        .HasColumnType("int")
                        .HasColumnName("uslugeID");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int")
                        .HasColumnName("voziloID");

                    b.HasKey("AutoservisId")
                        .HasName("PK_autoservis");

                    b.HasIndex("GradId");

                    b.HasIndex("UlogaId");

                    b.HasIndex("UslugeId");

                    b.HasIndex("VoziloId");

                    b.ToTable("Autoservis");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.ChatKlijentServi", b =>
                {
                    b.Property<int>("ChatKlijentServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChatKlijentServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatKlijentServisId"));

                    b.Property<int?>("AutoservisId")
                        .HasColumnType("int")
                        .HasColumnName("autoservis_id");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime")
                        .HasColumnName("datum");

                    b.Property<int?>("KlijentId")
                        .HasColumnType("int")
                        .HasColumnName("klijent_id");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("text")
                        .HasColumnName("sadrzaj");

                    b.HasKey("ChatKlijentServisId")
                        .HasName("pk_chat");

                    b.HasIndex("AutoservisId");

                    b.HasIndex("KlijentId");

                    b.ToTable("Chat_klijent_servis", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.ChatKlijentZaposlenik", b =>
                {
                    b.Property<int>("ChatKlijentZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChatKlijentZaposlenikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatKlijentZaposlenikId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime")
                        .HasColumnName("datum");

                    b.Property<int?>("KlijentId")
                        .HasColumnType("int")
                        .HasColumnName("klijent_id");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("text")
                        .HasColumnName("sadrzaj");

                    b.Property<int?>("ZaposlenikId")
                        .HasColumnType("int")
                        .HasColumnName("zaposlenik_id");

                    b.HasKey("ChatKlijentZaposlenikId")
                        .HasName("pk_chat2");

                    b.HasIndex("KlijentId");

                    b.HasIndex("ZaposlenikId");

                    b.ToTable("Chat_klijent_zaposlenik", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Drzava", b =>
                {
                    b.Property<int>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrzavaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrzavaId"));

                    b.Property<string>("NazivDrzave")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_drzave");

                    b.HasKey("DrzavaId")
                        .HasName("PK_drzava");

                    b.ToTable("Drzava", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.FirmaAutodijelova", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FirmaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adresa");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<int?>("GradId")
                        .HasColumnType("int")
                        .HasColumnName("gradID");

                    b.Property<int?>("IzvjestajId")
                        .HasColumnType("int")
                        .HasColumnName("izvjestajID");

                    b.Property<string>("NazivFirme")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_firme");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password_");

                    b.Property<string>("SlikaProfila")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("slika_Profila");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefon");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int")
                        .HasColumnName("ulogaID");

                    b.HasKey("FirmaId")
                        .HasName("PK_firma");

                    b.HasIndex("GradId");

                    b.HasIndex("IzvjestajId");

                    b.HasIndex("UlogaId");

                    b.ToTable("Firma_autodijelova", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Grad", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GradID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradId"));

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int")
                        .HasColumnName("drzavaID");

                    b.Property<string>("NazivGrada")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_grada");

                    b.HasKey("GradId")
                        .HasName("PK_grad");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Grad", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Izvjestaj", b =>
                {
                    b.Property<int>("IzvjestajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IzvjestajID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajId"));

                    b.HasKey("IzvjestajId")
                        .HasName("PK_izvjestaj");

                    b.ToTable("Izvjestaj", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KategorijaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("NazivKategorije")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_kategorije");

                    b.HasKey("KategorijaId")
                        .HasName("PK_kategorija");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Klijent", b =>
                {
                    b.Property<int>("KlijentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KlijentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlijentId"));

                    b.Property<string>("BrojTelefona")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("broj_telefona");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<int?>("GradId")
                        .HasColumnType("int")
                        .HasColumnName("gradID");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ime");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("password_");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prezime");

                    b.Property<string>("Spol")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("spol");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("KlijentId")
                        .HasName("PK_klijent");

                    b.HasIndex("GradId");

                    b.ToTable("Klijent", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Narudzba", b =>
                {
                    b.Property<int>("NarudzbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NarudzbaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaId"));

                    b.Property<DateTime?>("DatumIsporuke")
                        .HasColumnType("date")
                        .HasColumnName("datum_isporuke");

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("date")
                        .HasColumnName("datum_narudzbe");

                    b.Property<int?>("NarudzbaStavkeId")
                        .HasColumnType("int")
                        .HasColumnName("narudzbaStavkeID");

                    b.Property<int?>("PopustId")
                        .HasColumnType("int")
                        .HasColumnName("popustID");

                    b.Property<bool?>("ZavrsenaNarudzba")
                        .HasColumnType("bit")
                        .HasColumnName("zavrsena_narudzba");

                    b.HasKey("NarudzbaId")
                        .HasName("pk_n");

                    b.HasIndex("NarudzbaStavkeId");

                    b.HasIndex("PopustId");

                    b.ToTable("Narudzba", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.NarudzbaStavka", b =>
                {
                    b.Property<int>("NarudzbaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Narudzba_stavkaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarudzbaStavkaId"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cijena");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("kolicina");

                    b.Property<int?>("ProizvodId")
                        .HasColumnType("int")
                        .HasColumnName("proizvodID");

                    b.HasKey("NarudzbaStavkaId")
                        .HasName("pk_ns");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Narudzba_Stavka", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.PlacanjeAutoservisDijelovi", b =>
                {
                    b.Property<int>("PlacanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlacanjeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlacanjeId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime")
                        .HasColumnName("datum");

                    b.Property<double?>("Iznos")
                        .HasColumnType("float")
                        .HasColumnName("iznos");

                    b.Property<int?>("Posiljaoc")
                        .HasColumnType("int")
                        .HasColumnName("posiljaoc");

                    b.Property<int?>("Primalac")
                        .HasColumnType("int")
                        .HasColumnName("primalac");

                    b.HasKey("PlacanjeId")
                        .HasName("pk_pl");

                    b.HasIndex("Posiljaoc");

                    b.HasIndex("Primalac");

                    b.ToTable("placanje_autoservis_dijelovi", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Popust", b =>
                {
                    b.Property<int>("PopustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PopustID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PopustId"));

                    b.Property<int?>("AutoservisId")
                        .HasColumnType("int")
                        .HasColumnName("autoservis_id");

                    b.Property<int?>("FirmaAutodijelovaId")
                        .HasColumnType("int")
                        .HasColumnName("firma_autodijelovaID");

                    b.Property<double?>("VrijednostPopusta")
                        .HasColumnType("float")
                        .HasColumnName("vrijednost_popusta");

                    b.HasKey("PopustId")
                        .HasName("pk_popust");

                    b.HasIndex("AutoservisId");

                    b.HasIndex("FirmaAutodijelovaId");

                    b.ToTable("Popust", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProizvodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodId"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money")
                        .HasColumnName("cijena");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int")
                        .HasColumnName("kategorijaID");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("model");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<string>("OriginalniBroj")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("originalni_broj");

                    b.Property<int?>("ProizvodjacId")
                        .HasColumnType("int")
                        .HasColumnName("proizvodjacID");

                    b.Property<string>("Sifra")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sifra");

                    b.HasKey("ProizvodId")
                        .HasName("pk_proizvod");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("ProizvodjacId");

                    b.ToTable("Proizvod", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Proizvodjac", b =>
                {
                    b.Property<int>("ProizvodjacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProizvodjacID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodjacId"));

                    b.Property<string>("NazivProizvodjaca")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_proizvodjaca");

                    b.HasKey("ProizvodjacId")
                        .HasName("PK_proizvodjac");

                    b.ToTable("Proizvodjac", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Uloge", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UlogaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("NazivUloge")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_uloge");

                    b.HasKey("UlogaId")
                        .HasName("PK_uloga");

                    b.ToTable("Uloge", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Usluge", b =>
                {
                    b.Property<int>("UslugeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UslugeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UslugeId"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cijena");

                    b.Property<string>("NazivUsluge")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naziv_usluge");

                    b.Property<string>("Opis")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("opis");

                    b.HasKey("UslugeId")
                        .HasName("PK_usluge");

                    b.ToTable("Usluge", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Vozilo", b =>
                {
                    b.Property<int>("VoziloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoziloID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoziloId"));

                    b.Property<string>("GodisteVozila")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("godiste_vozila");

                    b.Property<string>("MarkaVozila")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marka_vozila");

                    b.Property<string>("VrstaVozila")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("vrsta_vozila");

                    b.HasKey("VoziloId")
                        .HasName("PK_vozilo");

                    b.ToTable("Vozilo", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZaposlenikID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikId"));

                    b.Property<int?>("AutoservisId")
                        .HasColumnType("int")
                        .HasColumnName("autoservisID");

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("date")
                        .HasColumnName("datum_rodjenja");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<int?>("FirmaAutodijelovaId")
                        .HasColumnType("int")
                        .HasColumnName("firma_autodijelovaID");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ime");

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("password_");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prezime");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int")
                        .HasColumnName("ulogaID");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("ZaposlenikId")
                        .HasName("PK_zaposlenik");

                    b.HasIndex("AutoservisId");

                    b.HasIndex("FirmaAutodijelovaId");

                    b.HasIndex("UlogaId");

                    b.ToTable("Zaposlenik", (string)null);
                });

            modelBuilder.Entity("FirmaAutodijelovaProizvod", b =>
                {
                    b.Property<int>("FirmaId")
                        .HasColumnType("int")
                        .HasColumnName("firmaID");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("int")
                        .HasColumnName("proizvodID");

                    b.HasKey("FirmaId", "ProizvodId")
                        .HasName("PK__FirmaAut__4F1EF5F45990B64A");

                    b.HasIndex("ProizvodId");

                    b.ToTable("FirmaAutodijelova_Proizvod", (string)null);
                });

            modelBuilder.Entity("ZaposlenikProizvod", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .HasColumnType("int")
                        .HasColumnName("zaposlenikID");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("int")
                        .HasColumnName("proizvodID");

                    b.HasKey("ZaposlenikId", "ProizvodId")
                        .HasName("PK__Zaposlen__50FD668EDF7047CD");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Zaposlenik_Proizvod", (string)null);
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Autoservi", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Grad", "Grad")
                        .WithMany("Autoservis")
                        .HasForeignKey("GradId")
                        .HasConstraintName("fk_autoservis_grad");

                    b.HasOne("CarCareHub.Services.Database.Uloge", "Uloga")
                        .WithMany("Autoservis")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("fk_uloga_autoservis");

                    b.HasOne("CarCareHub.Services.Database.Usluge", "Usluge")
                        .WithMany("Autoservis")
                        .HasForeignKey("UslugeId")
                        .HasConstraintName("fk_u_a");

                    b.HasOne("CarCareHub.Services.Database.Vozilo", "Vozilo")
                        .WithMany("Autoservis")
                        .HasForeignKey("VoziloId")
                        .HasConstraintName("fk_v_a");

                    b.Navigation("Grad");

                    b.Navigation("Uloga");

                    b.Navigation("Usluge");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.ChatKlijentServi", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Autoservi", "Autoservis")
                        .WithMany("ChatKlijentServis")
                        .HasForeignKey("AutoservisId")
                        .HasConstraintName("fk_autoservis_chat");

                    b.HasOne("CarCareHub.Services.Database.Klijent", "Klijent")
                        .WithMany("ChatKlijentServis")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("fk_klijent_chat");

                    b.Navigation("Autoservis");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.ChatKlijentZaposlenik", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Klijent", "Klijent")
                        .WithMany("ChatKlijentZaposleniks")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("fk_klijent_chat2");

                    b.HasOne("CarCareHub.Services.Database.Zaposlenik", "Zaposlenik")
                        .WithMany("ChatKlijentZaposleniks")
                        .HasForeignKey("ZaposlenikId")
                        .HasConstraintName("fk_zaposlenik_chat2");

                    b.Navigation("Klijent");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.FirmaAutodijelova", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Grad", "Grad")
                        .WithMany("FirmaAutodijelovas")
                        .HasForeignKey("GradId")
                        .HasConstraintName("fk_autoservis_grads");

                    b.HasOne("CarCareHub.Services.Database.Izvjestaj", "Izvjestaj")
                        .WithMany("FirmaAutodijelovas")
                        .HasForeignKey("IzvjestajId")
                        .HasConstraintName("fk_i_fad");

                    b.HasOne("CarCareHub.Services.Database.Uloge", "Uloga")
                        .WithMany("FirmaAutodijelovas")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("fk_uloga_firmaautodijelova");

                    b.Navigation("Grad");

                    b.Navigation("Izvjestaj");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Grad", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Drzava", "Drzava")
                        .WithMany("Grads")
                        .HasForeignKey("DrzavaId")
                        .HasConstraintName("fk_d_g");

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Klijent", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Grad", "Grad")
                        .WithMany("Klijents")
                        .HasForeignKey("GradId")
                        .HasConstraintName("fk_klijent_grad");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Narudzba", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.NarudzbaStavka", "NarudzbaStavke")
                        .WithMany("Narudzbas")
                        .HasForeignKey("NarudzbaStavkeId")
                        .HasConstraintName("fk_ns_n");

                    b.HasOne("CarCareHub.Services.Database.Popust", "Popust")
                        .WithMany("Narudzbas")
                        .HasForeignKey("PopustId")
                        .HasConstraintName("fk_n_p");

                    b.Navigation("NarudzbaStavke");

                    b.Navigation("Popust");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.NarudzbaStavka", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Proizvod", "Proizvod")
                        .WithMany("NarudzbaStavkas")
                        .HasForeignKey("ProizvodId")
                        .HasConstraintName("fk_ns_p");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.PlacanjeAutoservisDijelovi", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Autoservi", "PosiljaocNavigation")
                        .WithMany("PlacanjeAutoservisDijelovis")
                        .HasForeignKey("Posiljaoc")
                        .HasConstraintName("fk_plad");

                    b.HasOne("CarCareHub.Services.Database.FirmaAutodijelova", "PrimalacNavigation")
                        .WithMany("PlacanjeAutoservisDijelovis")
                        .HasForeignKey("Primalac")
                        .HasConstraintName("fk_primad");

                    b.Navigation("PosiljaocNavigation");

                    b.Navigation("PrimalacNavigation");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Popust", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Autoservi", "Autoservis")
                        .WithMany("Popusts")
                        .HasForeignKey("AutoservisId")
                        .HasConstraintName("fk_autoservis_popust");

                    b.HasOne("CarCareHub.Services.Database.FirmaAutodijelova", "FirmaAutodijelova")
                        .WithMany("Popusts")
                        .HasForeignKey("FirmaAutodijelovaId")
                        .HasConstraintName("fk_firma_Popust");

                    b.Navigation("Autoservis");

                    b.Navigation("FirmaAutodijelova");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Proizvod", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Proizvods")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("fk_kategorija_proizvod");

                    b.HasOne("CarCareHub.Services.Database.Proizvodjac", "Proizvodjac")
                        .WithMany("Proizvods")
                        .HasForeignKey("ProizvodjacId")
                        .HasConstraintName("fk_proizvodjac_proizvod");

                    b.Navigation("Kategorija");

                    b.Navigation("Proizvodjac");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Zaposlenik", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Autoservi", "Autoservis")
                        .WithMany("Zaposleniks")
                        .HasForeignKey("AutoservisId")
                        .HasConstraintName("fk_zaposlenik_autoservis");

                    b.HasOne("CarCareHub.Services.Database.FirmaAutodijelova", "FirmaAutodijelova")
                        .WithMany("Zaposleniks")
                        .HasForeignKey("FirmaAutodijelovaId")
                        .HasConstraintName("fk_firma_zaposlenik");

                    b.HasOne("CarCareHub.Services.Database.Uloge", "Uloga")
                        .WithMany("Zaposleniks")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("fk_uloga_zaposlenik");

                    b.Navigation("Autoservis");

                    b.Navigation("FirmaAutodijelova");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("FirmaAutodijelovaProizvod", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.FirmaAutodijelova", null)
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .IsRequired()
                        .HasConstraintName("FK__FirmaAuto__firma__7F2BE32F");

                    b.HasOne("CarCareHub.Services.Database.Proizvod", null)
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .IsRequired()
                        .HasConstraintName("FK__FirmaAuto__proiz__00200768");
                });

            modelBuilder.Entity("ZaposlenikProizvod", b =>
                {
                    b.HasOne("CarCareHub.Services.Database.Proizvod", null)
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .IsRequired()
                        .HasConstraintName("FK__Zaposleni__proiz__7C4F7684");

                    b.HasOne("CarCareHub.Services.Database.Zaposlenik", null)
                        .WithMany()
                        .HasForeignKey("ZaposlenikId")
                        .IsRequired()
                        .HasConstraintName("FK__Zaposleni__zapos__7B5B524B");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Autoservi", b =>
                {
                    b.Navigation("ChatKlijentServis");

                    b.Navigation("PlacanjeAutoservisDijelovis");

                    b.Navigation("Popusts");

                    b.Navigation("Zaposleniks");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Drzava", b =>
                {
                    b.Navigation("Grads");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.FirmaAutodijelova", b =>
                {
                    b.Navigation("PlacanjeAutoservisDijelovis");

                    b.Navigation("Popusts");

                    b.Navigation("Zaposleniks");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Grad", b =>
                {
                    b.Navigation("Autoservis");

                    b.Navigation("FirmaAutodijelovas");

                    b.Navigation("Klijents");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Izvjestaj", b =>
                {
                    b.Navigation("FirmaAutodijelovas");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Proizvods");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Klijent", b =>
                {
                    b.Navigation("ChatKlijentServis");

                    b.Navigation("ChatKlijentZaposleniks");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.NarudzbaStavka", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Popust", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Proizvod", b =>
                {
                    b.Navigation("NarudzbaStavkas");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Proizvodjac", b =>
                {
                    b.Navigation("Proizvods");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Uloge", b =>
                {
                    b.Navigation("Autoservis");

                    b.Navigation("FirmaAutodijelovas");

                    b.Navigation("Zaposleniks");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Usluge", b =>
                {
                    b.Navigation("Autoservis");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Vozilo", b =>
                {
                    b.Navigation("Autoservis");
                });

            modelBuilder.Entity("CarCareHub.Services.Database.Zaposlenik", b =>
                {
                    b.Navigation("ChatKlijentZaposleniks");
                });
#pragma warning restore 612, 618
        }
    }
}
